name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Verify success
        id: verify-success
        uses: ./
        with:
          local-verify-files-path: tests/success.json
          install: true
          cache-pip: true
          write-summary: true
          result-artifact-prefix: success
          result-file-name: result.json

      - name: Test success
        run: |
          [ "${{ steps.verify-success.outputs.is-success }}"  = "true" ]
          [ $(jq '.files|length' "$RUNNER_TEMP/result.json") = 4 ]

      - name: Verify failure
        id: verify-failure
        uses: ./
        with:
          local-verify-files-path: tests/failure.json
          write-summary: true
          result-artifact-prefix: failure
          result-file-name: result.json

      - name: Test failure
        run: |
          [ "${{ steps.verify-failure.outputs.is-success }}"  = "false" ]
          [ $(jq '.files|length' "$RUNNER_TEMP/result.json") = 1 ]

      - name: Verify success split-0
        id: verify-success-split-0
        uses: ./
        with:
          local-verify-files-path: tests/success.json
          write-summary: true
          result-artifact-prefix: split2
          result-file-name: result.json
          split-size: 2
          split-index: 0
      - name: Test split-0
        run: |
          [ "${{ steps.verify-success-split-0.outputs.is-success }}"  = "true" ]
          [ $(jq '.files|length' "$RUNNER_TEMP/result.json") = 2 ]

      - name: Verify success split-1
        id: verify-success-split-1
        uses: ./
        with:
          local-verify-files-path: tests/success.json
          write-summary: true
          result-artifact-prefix: split2
          result-file-name: result.json
          split-size: 2
          split-index: "01"
      - name: Test split-1
        run: |
          [ "${{ steps.verify-success-split-1.outputs.is-success }}"  = "true" ]
          [ $(jq '.files|length' "$RUNNER_TEMP/result.json") = 2 ]

      - name: Verify success split-over
        id: verify-success-split-over
        uses: ./
        with:
          local-verify-files-path: tests/success.json
          write-summary: true
          result-artifact-prefix: split5
          result-file-name: result.json
          split-size: 10
          split-index: 4
      - name: Test split-over
        run: |
          [ "${{ steps.verify-success-split-over.outputs.is-success }}"  = "true" ]
          [ $(jq '.files|length' "$RUNNER_TEMP/result.json") = 0 ]
